Setup db config
jkhirano/consume-more-stuff pull request #11
Opened 2019-10-25 07:58 UTC by rianmueller

Seeds for items and images are still incomplete, please review the rest of the seeds and migrations.

2019-10-25 09:01 UTC, danieltichiyama requested changes
LGTM except one suggestion in the price column of items.

2019-10-25 09:01 UTC, danieltichiyama commented on server/database/migrations/20191024203909_create-items.js
> +    table.decimal("price");
should add the number of digits possible after the decimal as a second parameter so that the price never gets more specific than the hundredths place, for example $100.99 and not $100.9999.

2019-10-25 09:24 UTC, danieltichiyama commented on server/database/migrations/20191024203631_create-userStatuses.js
> +    table.string("status").notNullable();
can you change the name of this column to "userStatus", just so when we write our bookshelf routes it's clearly separate from the other itemStatus?

2019-10-25 09:25 UTC, danieltichiyama commented on server/database/migrations/20191024201543_create-itemStatuses.js
> +    table.string("status").notNullable();
can you change this to "itemStatus" so that it's clearly differentiated from userStatus?

2019-10-26 18:53 UTC, rianmueller commented on server/database/migrations/20191024203909_create-items.js
> +    table.decimal("price");
It's 2 by default, you only need to specify when you want something other than 2 decimal places. http://knexjs.org/#Schema-decimal

2019-10-26 18:58 UTC, rianmueller commented on server/database/migrations/20191024203631_create-userStatuses.js
> +    table.string("status").notNullable();
Done

2019-10-26 18:59 UTC, rianmueller commented on server/database/migrations/20191024201543_create-itemStatuses.js
> +    table.string("status").notNullable();
Done.

2019-10-26 19:00 UTC, closed without merging