Navigation component
jkhirano/consume-more-stuff pull request #14
Opened 2019-10-29 06:11 UTC by danieltichiyama

This component is set up to exist at the App level, the same level as the HabitList component.  It has functionality to toggle a global state property called display, which houses boolean values that represent the open state of the other UnAuth components (i.e. a true values = open, false = closed);

This component does not reach into server.

test it:
- [ ] open project in browser
- [ ] open console
- [ ] click on any of the links
- [ ] you should see a console log of the this.props.display, and all values should be toggled to false expect for the one you clicked on.

it can be tested further when the other components have foundational builds and are ready to receive open/close functionality.

2019-10-29 07:16 UTC, andrewobx requested changes
Everything works as advertised. Just a small thing for the TOGGLE case in the reducer. See attached notes.

2019-10-29 07:16 UTC, AndrewObiano commented on src/App/App.js
> +import NavigationComponent from "../containers/NavigationComponent.jsx/NavigationComponent";
Not really a problem, but I tried to wrangle the directory to only say NavigationComponent once but couldn't get React to compile it. The other files seems to be arranged correctly.

2019-10-29 07:16 UTC, AndrewObiano commented on src/reducers/index.js
> +    case TOGGLE:
The case toggles the correct display key in the global state but it doesn't seem to revert it back. Was this happening for you too?

2019-10-29 08:39 UTC, danieltichiyama commented on src/App/App.js
> +import NavigationComponent from "../containers/NavigationComponent.jsx/NavigationComponent";
yeah, I noticed that too, but I didn't try to change it to the naming format we usually use... it got that way, I think, because I added the component to the render function and it was an automatic add (like the shortcut from angular), dunno what it'll effect if anything.

2019-10-29 08:41 UTC, danieltichiyama commented on src/reducers/index.js
> +    case TOGGLE:
Yeah, I built it to do that.  It will only change the global state to true for whatever navigation button is pressed.  Since it's a navigation bar, I figured that even if a user clicked on the same button twice, that view should stay open.

2019-10-30 04:18 UTC, AndrewObiano commented on src/reducers/index.js
> +    case TOGGLE:
Now that I looked at lines 21-27 again I realized how obvious it was.. I'm guessing we'll be making another "exit" function to counter this later on.

2019-10-30 04:19 UTC, andrewobx approved these changes

2019-10-30 05:37 UTC, jkhirano commented on src/App/App.js
> +import NavigationComponent from "../containers/NavigationComponent.jsx/NavigationComponent";
I think it's because the name of the folder has ".jsx"?

2019-10-30 06:12 UTC, jkhirano approved these changes

2019-10-30 22:33 UTC, merged