redux-header
jkhirano/consume-more-stuff pull request #15
Opened 2019-10-29 06:54 UTC by kcbangi

setup redux, header, and made some changes on the list of habits and move it to reducers.

2019-10-29 08:56 UTC, danieltichiyama requested changes
Can you please provide details on how your changes should work and, if possible, instructions for how to test them?

2019-10-29 08:56 UTC, danieltichiyama commented on src/index.js
> +// import { createStore, applyMiddleware, compose } from 'redux';
it looks like you set it up to not use the applyMiddleware or redux-thunk module.  Can you explain why you decided to do it that way?

2019-10-29 08:56 UTC, danieltichiyama commented on src/reducers/index.js
> +import { LOAD_HABIT } from '../actions';
change to LOAD_HABITS to keep the same as the function's name.

2019-10-29 08:56 UTC, danieltichiyama commented on src/reducers/index.js
> +      return state.books;
state.books doesn't exist.  and I'm pretty sure all of these cases in the switch statement need to return an object.  The object returned becomes the new state, so it'd have to include all of the old state things, and whatever changes your function made.  I believe that's why we need to use Object.assign(), to combine the old and new state objects.

2019-10-29 08:56 UTC, danieltichiyama commented on src/actions/index.js
> +export const LOAD_HABIT = 'LOAD_HABIT';
change the variable to LOAD_HABITS and the value to "LOAD_HABITS" to keep it the same name as the function loadHabits().

2019-10-29 08:56 UTC, danieltichiyama commented on src/actions/index.js
> +export function loadHabits(payload) {
you don't need the payload parameter if there is no parameter being passed into it from the component.

2019-10-29 08:56 UTC, danieltichiyama commented on src/actions/index.js
> +    payload
set payload to equal null

2019-10-31 05:22 UTC, danieltichiyama approved these changes
please check with Janelle's comment.

2019-10-31 05:23 UTC, jkhirano approved these changes
Just need to fix the App.js navigation component and then you can merge

2019-10-31 05:23 UTC, jkhirano commented on src/App/App.js
>  import NavigationComponent from "../containers/NavigationComponent.jsx/NavigationComponent";
This threw an error. It should be revised to:
```
import NavigationComponent from "../containers/NavigationComponent";
```

2019-10-31 05:43 UTC, merged